===board===채용관련 테이블 

  CREATE TABLE "SCOTT"."BOARD" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"WRITEDATE" DATE DEFAULT SYSDATE, 
	"READCNT" NUMBER DEFAULT 0, 
	"FILENAME" VARCHAR2(300 BYTE), 
	"FILEPATH" VARCHAR2(300 BYTE), 
	 CONSTRAINT "BOARD_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRG_BOARD" 
	BEFORE INSERT ON board
	FOR EACH ROW
BEGIN
	SELECT seq_board.NEXTVAL INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "SCOTT"."TRG_BOARD" ENABLE;

===board_comment===채용댓글

  CREATE TABLE "SCOTT"."BOARD_COMMENT" 
   (	"ID" NUMBER, 
	"PID" NUMBER NOT NULL ENABLE, 
	"WRITER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"WRITEDATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "BOARD_COMMENT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "BOARD_COMMENT_PID_FK" FOREIGN KEY ("PID")
	  REFERENCES "SCOTT"."BOARD" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "BOARD_COMMENT_WRITER_FK" FOREIGN KEY ("WRITER")
	  REFERENCES "SCOTT"."MEMBER" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRG_BOARD_COMMENT" 
    BEFORE INSERT ON board_comment
    FOR EACH ROW
BEGIN
    SELECT seq_board_comment.NEXTVAL INTO :NEW.id FROM dual;
END;
/
ALTER TRIGGER "SCOTT"."TRG_BOARD_COMMENT" ENABLE;


===customer===유지보수 관련 테이블


  CREATE TABLE "SCOTT"."CUSTOMER" 
   (	"ID" NUMBER, 
	"WRITER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRODUCT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USAGEPERIOD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"WEBHOSTING" VARCHAR2(10 BYTE), 
	"HOSTINGTYPE" VARCHAR2(20 BYTE), 
	"SERVERSCALE" VARCHAR2(10 BYTE), 
	"WEBSTORAGE" VARCHAR2(10 BYTE), 
	 CONSTRAINT "SERVICE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRG_CUSTOMER" 
    BEFORE INSERT ON customer   -- customer 테이블에 INSERT 되기 전에
    FOR EACH ROW    -- 각 행에 대해
BEGIN
    SELECT seq_customer.NEXTVAL INTO :new.id FROM dual;  -- dual에서 시퀀스 값을 가져와 새로운 행의 id에 할당
END;
/
ALTER TRIGGER "SCOTT"."TRG_CUSTOMER" ENABLE;


===member===

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(10 BYTE) DEFAULT 'male' NOT NULL ENABLE, 
	"BIRTH" VARCHAR2(30 BYTE), 
	"POST" VARCHAR2(7 BYTE), 
	"ADDR" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TEL" VARCHAR2(20 BYTE), 
	"ADMIN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	 CONSTRAINT "MEMBER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

===notice=== 유지보수 문의

  CREATE TABLE "SCOTT"."NOTICE" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"WRITER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"WRITEDATE" DATE DEFAULT SYSDATE, 
	"READCNT" NUMBER DEFAULT 0, 
	"FILENAME" VARCHAR2(300 BYTE), 
	"FILEPATH" VARCHAR2(300 BYTE), 
	"ROOT" NUMBER, 
	"STEP" NUMBER DEFAULT 0, 
	"INDENT" NUMBER DEFAULT 0, 
	 CONSTRAINT "NOTICE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRG_NOTICE" 
    BEFORE INSERT ON notice
    FOR EACH ROW
BEGIN
    SELECT seq_notice.NEXTVAL INTO:NEW.id FROM dual;
END;
/
ALTER TRIGGER "SCOTT"."TRG_NOTICE" ENABLE;

===QNA=== 프로젝트 문의


  CREATE TABLE "SCOTT"."QNA" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"SORTATION" VARCHAR2(200 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"METHOD" VARCHAR2(50 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"CNAME" VARCHAR2(50 BYTE), 
	"BUDGET" VARCHAR2(50 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"LIMITDATE" VARCHAR2(50 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"URL" VARCHAR2(100 BYTE), 
	"WRITER" VARCHAR2(20 BYTE) DEFAULT 'default' NOT NULL ENABLE, 
	"WRITEDATE" DATE DEFAULT SYSDATE, 
	"READCNT" NUMBER DEFAULT 0, 
	"FILENAME" VARCHAR2(300 BYTE), 
	"FILEPATH" VARCHAR2(300 BYTE), 
	"ROOT" NUMBER, 
	"STEP" NUMBER DEFAULT 0, 
	"INDENT" NUMBER DEFAULT 0, 
	 CONSTRAINT "QNA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SCOTT"."TRG_QNA" 
    BEFORE INSERT ON qna
    FOR EACH ROW
BEGIN
    SELECT seq_qna.NEXTVAL INTO:NEW.id FROM dual;
END;
/
ALTER TRIGGER "SCOTT"."TRG_QNA" ENABLE;

